version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile

    container_name: buyaladdin-nginx
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/srv/test
      - ./log:/var/log/docker
    command:
      gunicorn --bind 0.0.0.0:5000 wsgi:app

    expose:
      - "5000"
      - "8082"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dockerfile
    restart: always
    volumes:
      - .:/srv/test
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8082:8082"
    depends_on:
      - app
